---
title: 'Lecture 6: Multivariate Normal demo'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(rstan)
#setwd("/Volumes/GoogleDrive/My Drive/Teaching/STAT534/Lectures/Lecture 4. Stan and GP")
```


#### Multivariate Normal Distribution

First we will start with the a bivariate normal distribution:
y ~ N(theta,sigma), where theta is a mean vector and sigma = sigmasq * I is a covariance matrix.

To provide a motivating context, not consider jointly estimating the temperature at Bridger Bowl *and* Big Sky Resort.


##### 1. Simulate independent bivariate normal

Simulate a set of temperature values from each location, where the temperature values are independent (sigma = sigmasq * I)


Then create a few graphs to show marginal distribution of temperature as well as how the temperatures evolve in time.

##### 2. Simulate correlated bivariate normal

Simulate a set of temperature values from each location, where the temperature values are not independent (sigma = sigmasq * H), where H is a correlation matrix. (Note there are some constraints we will discuss later)

Then create a few graphs to show marginal distribution of temperature as well as how the temperatures evolve in time.

##### 3. Write STAN code for bivariate normal

Write stan code that will allow you to estimate theta and sigma (including H)

```{stan output.var='multi_norm', eval = F}
data {
  int<lower=0> p;
  int<lower=0> N;
  matrix[N,p] y;
}







```

##### 4. Use STAN to estimate bivariate normal parameters

Use your stan code to estimate theta and sigma (including H and sigmasq)




##### 5. Thoughts About Correlation

In many statistical models there is an assumption about independence. When independence is violated, uncertainty is under estimated and in incorrect inferences can be made.

While lack of independence often has a negative connotation, in spatial statistics we can actually exploit correlation. For instance, by knowing the temperature at the weather station at Bozeman High School or Bridger Bowl, we can estimate temperature at other locations.


#### Conditional Normal distribution

Now there is one more location that we are interested in learning the temperature, maybe Rendezvous Ski Trails in West Yellowstone.

Let's assume that 
$$\begin{bmatrix} y_{bridger}\\ y_{big sky}\\ y_{rendezvous} \end{bmatrix} \sim N \left(\begin{bmatrix} 15 \\ 15 \\ 15\end{bmatrix}, 100\begin{bmatrix} 1 & .3 & .2 \\ .3 & 1 & .5 \\ .2 & .5 & 1
\end{bmatrix} \right)$$

###### 1. Simulate one data point for Bridger and Big Sky

Simulate a single realization from the distribution for Bridger and Big Sky (ignoring Rendezvous for now).


###### 2. Estimate Rendezvous, conditional on the data point from Bridger and Big Sky

Conditional on the values from the previous question, construct the distribution for the Rendezvous temperature. Add this to a graph with a marginal temperature. Rerun this a few times (with a different seed) to see how it changes.
